package frames

var Brittany = DefaultFrameType(brittanyFrame)

var brittanyFrame = []string{
	`hhhoohhooooooooooo//////////////////////////////////////////////////////////////
hhhhoooooooooooooooo////////oNo/////////////////////////////////////////////////
oooooooooooooooooooooooooooooNNooo////////////////////////////////////////oooooo
oooooooooooooooooooooooooooohddhNooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohsdNoNhooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohsdshhhdhooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohsdsNoooNhoooooooooooooooooooooooooooooooooooooooooo
hhhhhhhhoooooooooooooooooooohsNsdohhhodNoooooooooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNdhooooohhhhoooooooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNN///..../hshhhhhhhhhhoooooooooooooooooooooooooohh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNNNhhhoo///hdNhhoooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNNNNNdNhhhho/hdhoooooooooooooooooooooooooooooooooo
o/oo/////////////////////////dN/.........././ho/////////////////////////////////
/////////////////////////////ddooooooo//..o/.///////////////////////////////////
/////////////////////////////ddddddddddhhhhNo./..///////////////////////////////
/////////////////////////////No//////ooo////..//..//////////////////////////////
/////////////////////////////ho////////......../h///////////////////////////////
//////////////////////ooooooohdooooooo/////////NNd//////////////////////.///////
//oohhhNNNdddddssssssssssdddddsdNNNNhNNhhhhhhhNdNddNsssdddddddNNNNhhhhooo///////
sssddNNNhhhhooooo////////////osdo////////////////./N/////oooooohhhhhNNNdddsssddN
//////////////////oooohhhhhhhNsshhhhhoooooooooooo/.ooo/////////////////////////o
//oohhhNNdddsss--------------s---------sssdNNNNNdN/Ns-----sssdddNNNNhhooo/////oo
ds-----------ssssssddddsssssss--ssssssssdddddddddN/dddddddddsssss--------sssdNhh`,
	`hhhooooooooooooooo////////////oo////////////////////////////////////////////////
ooooooooooooooooooooooooooooooNdo///////////////////////////////////////////ooo/
ooooooooooooooooooooooooooooooNdNhoooooooooooooo//////////o/o/oooooooooooooooooo
ooooooooooooooooooooooooooooooddsNNhoooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNsdNNhhoooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooddddNNhNNhoooooooooooooooooooooooooooooooooooooooo
hhhoooooooooooooooooooooooooooddNdhddNNoNNoooooooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhdhNdshohNNooooooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhh////ooo/NhNNhhhhohooooooooooooooooooooooooooho
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhh//////./ohNhhNhhhhooooooooooooooooooohhoohhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhddddddddN/...../ooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooNsoooooohhNNNho//.../ooooooooooooooooooooooooooooo
//////////////////////////////Ns/..........////hhoo/.///////////////////////////
//////////////////////////////NdNNNNNNNhhhhoo/..//ohho//////////////////////////
//////////////////////////////hNhhhhhNNdddssssdho/...oNo////////////////////////
//////////////////////////////ho/........///ooooooho/..ho///////////////////////
//////////////////////////////oNo/////////......../ohho/No///////./.....///////.
///////////ooohhhhNNNNNddddddddsdNNNNNhhhhhhhhNNNh//.oohho//////////////////////
NNddddssssssddddNNNNhhhhhhhoooosdhoooooooooooohhhhh//...hN/ddsssssdddddNNNhhhoo/
Nhhhoooo//////////////////////odso/////////////////////..oh////////ooooohhhNNddd
//////////ooohhhNNNNddddsssssss--ssssssdddddddddddNNhhooo///oo//////////////////
hhNdddss------------ssssssssssssssssssssssssssssssssssddNNood-----sssddNNhhhooo/
------ssssddddddsssssss-----         -----------sssssddddddNddddddssss--------ss
`, `ooooooooooooooo/////////////////////////////////////////////////////////////////
oooooooooooooooo//////////////oo////////////////////////////////////////////////
ooooooooooooooooooooooooooooooddooo/////////////////////////////////////oooooooo
ooooooooooooooooooooooooooooooNdNooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooddshoNNNhooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNsdhhohhdNhoooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNddNN/hhhhdddhooooooooooooooooooooooooooooooooooo
hhhhhhooooooooooooooooooooooooddNdNNhhooohhNdhNhoooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhNhNdN/hhhooNooNNooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddho//////////oo/o////ooooooooooooooooooooooohoooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhNshhoooo///....../oo/.//hooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhNshdddddddNhhooooo//oo../NNooooooooooooooooooooooo
oooooooooooooooo//o//o/o//o/ooNso////ooo///oooooohhhho/.Ndo//o//////////////////
//////////////////////////////hso/////............/ohhhhoNd/////////////////////
//////////////////////////////hdddddddddddNhhhoo///./ohhNdd/////////////////////
//////////////////////////////oNooooohhohhhoooooooho.../ohdh///////.////////////
///////////////////////////////o//................./o...../hN///////////////////
///////////////////////////////Nh//////////////...../hoo/.../o/////.....////////
///////oohhhNNNNNdddddsssssssssssdNNNNNNNNNNNNNNNhhh/ohhhhoNNNNhhhhoooo/////////
dddssssdddNNNhhhhhoooooo///////Nso///////////////////..//ohoohhhhNNNddddsddddddN
ooo/////////////////////oooooooNshoooooo//////////////....///////////////////ooo
//////ooohhNNNdddssss------------------------sssddNNNhhhhNddddNNNhhhoooo////////
ohNds-------------ssssssddddddss-ssssssdddddddddddddddddddssss---------sssddNhho
`, `oooooooooooo////////////////////////////////////////////////////////////////////
ooooooooooooo////////////////oNo////////////////////////////////////////////////
ooooooooooooooooooooooooooooohdNooooo/////////////////////////////oooooooooooooo
ooooooooooooooooooooooooooooohdddhhNhooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohsNdNhhhhhhoooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohsNdNddooohhhNNhooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohsNddhNhNoooNNNhoNhoooooooooooooooooooooooooooooooo
hhooooooooooooooooooooooooooohsNddodddhhooohoNNhhhoooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdNNoooooohoo/hNohN.NNooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddN////......///hNhoddhoooooooooooooooohhhhooohhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddNNNNNNNNNNh/.../ohNddhoooooooooooooooooooooooooo
hhhhhhhhhhhhhhhhohooooooooooooNdhhhhhhhNNNdNoo//..//oNooooooooooo////o//////////
//////////////////////////////Ns/..........////ooo/../h/////////////////////////
//////////////////////////////hdhhhhhhhhoooo/.../ohh/./Nh///////////////////////
//////////////////////////////odNNNNNNdddddssNo..../ho./ddNo////////////////////
///////////////////////////////h/.......///////oo/...ho..ohNN///////////////////
///////////////////////////////No/////..........ohh/./hh/../o///////////////////
////////////////////oooohhhhNNNddhhhhhhhhhhhooooo//oohhNNNhhhhhhhooooo//////////
/////oohhNNNdddssssssddddNNNNhhdsNhoooooooooooooo/./hh/oohhhhNNNNNNddddddddddddN
ddssssddNNNhhooo///////////////hsh///////////////////o////////////////////////o/
ooo///////////////ooohhhNNNNdddd-sdddddddddddNNhhho/hdddddNNNNNhhhhoooo/////////
/////oohhNNdddss----------ssssss-ssssssssssssddddNhhdddddssssssssssssssssssssddo
/hNds----------sssddddssssss-----   ----------sdddNhdsssssssddddddssdddddddddssh
`, `ooooooo//////////////////////oh/////////////////////////////////////////////////
oooooooooo///////////////////hdh////////////////////////////////////////////////
ooooooooooooooooooooooooooooohddhoooo////////////////////////////o/ooooooooooooo
ooooooooooooooooooooooooooooohdsNhddNhhhoooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohdNdhhhdhNNNhNNhhhooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohshdNNoNdsNNhhhhohdo//ooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohshdNhhNhdhNddhohhhhhhhho//oooooooooooooooooooooooo
ooooooooooooooooooooooooooooohshNhNNN/NdsdNsdNhh/.../oo/./oooooooooooooooooooooo
hhhhhhhhhhhhhhhhhhhooooooohhhhsNh///oohhNhhdsdoNhoo///....//oooooooooooooooooooo
oohhhhhhhhhhhhhhhhhooooohhhhhhdNho/.......///oohhhhhhhhoooo/./oooooooooooooooooo
hhhhooooooooooooooooooooooooohdNhdddhhhhooo/o//////...//////../ooooooooooooooooo
ooooooooooooooooooooooooooooooddoohhhhhNNhhhNNdddNNNNho////....hho//////////////
//////////////////////////////Nd/...../......//ohNNNdddNNhhhh//oo///////////////
//////////////////////////////NdNNhNNhhhhhoooo///...............////////////////
//////////////////////////////hhhhhhddNNNddssssdNhhoooooooooooooho//////////////
//////////////////////////////o/....../...../////o/////ooohhhNhhhNN/////////////
//////////////////////////////oNo/////./////.......///............//////////////
//////////////ooohhhNNNNNNddddNdNNNNNNNhNNNNNhhhhhhNNNNNNNNNNhhhhhooooo/////////
/oohNNNdddsssssdddNNNhhhhhooooodso///////////////oooooooohhhhhhhNNNNdddddddddddN
sddNNhhooo/////////////////////Nso///////////////////////////////////////////ooo
/////////////ooohhhNNNddddssssss-ssssddssssssssssssssddddddNNNNhhhhoooo/////////
//ohhNNddsss--------ssssssssssss-sssssssddddddddddddddddddsssssssss-ssssssssddNN
s---------sssdddddddsssss----  -         -------------sssssddddddddsdddddddssss-
`, `ooo///////////////////////////ho////////////////////////////////////////////////
ooo//////////////////////////odNo///////////////////////////////////////////////
oooooooooooo/////////////////oNdNhhho/////////////////////////////////////////oo
oooooooooooooooooooooooooooooodNdNohNhhooooooo///////////o/o/ooooooooooooooooooo
oooooooooooooooooooooooooooooodNdNhNhh/NNhhhoooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNdNNhohhhohNNNhohoooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNNNhdNdNhoooohoNhNNNhoooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooodNNhoNdNhodNh/hhhoN//ohhhooooooooooooooooooooooooo
ooooooooooooooooooooooooooooohddh/....///////oo/hNho/////ooooooooooooooooooooooo
ooooooohhhhoooooooooooooooooohddhoo///////......../ooohoo//ooooooooooooooooooooo
ooooooooooooooooooooooooooooooNdhddNddddNNNNhhooo///...//ohh//oooooooooooooooooo
ooooooooooooooooooooooooooooooNdo/ooooooooooohoooooooohho../o////oo/////////////
//////////////////////////////hd......................//ohho/.ohh///////////////
//////////////////////////////hddNNNNNNNNNNhhhooo///......./ohooohNo////////////
///////////////../////////////oNhhhhhhhhhhhhNNNdddhhhhoooooo/../hhNd////////////
//////////////////////////////o/................///////////oho/../h/////////////
///////////////////////////////Nh/////////...................ooo..//////////////
/////////////ooohhhNNNNNNddddddddNNNNNNNNNNNhhNNNNNNhhhoooo/..hhooooo///////////
ohhNNddddssssddddNNNhhhhhoooooodso//////////////oooooooooooo//hhNNNddddddddddNNN
ddNNhhooo//////////////////////Nso//////////////////////////////////////////oooo
////////////ooohhhNNNNddddssssss-sssssssssssssssssddddNNhhhhhhhhhoooo///////////
/ohhNNddsss--------ssssssssssssssssssdddddddddddddddddddddddsssssss-ssssssdddNNN
--------ssssdddddddddssss----  --      -------------sssssddddddddddsddddddsssssd
`, `/////////////////////////////hh/////////////////////////////////////////////////
o////////////////////////////NNo////////////////////////////////////////////////
oooooooooooo////////////////oNdNho//////////////////////////////////////////oooo
oooooooooooooooooooooooooooooddNhhNhoooooo////////////////oooooooooooooooooooooo
oooooooooooooooooooooooooooooddNhoohNhoooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooddshooohhNhhooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooddddoohoooddNhhoooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooodddNoohoohhhoNNo//ooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooNdN/.....//hNNNho/.//oooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooNshhooo///./h/hddNNo////ooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooNsNddddNhhhoo/oNddssNhoo//ooooooooooooooooooooooooo
ooooooooooooooooooooooooo//o/hs//////////oh.../hNdsdNo/oo///////////////////////
/////////////////////////////hd//////....../....../ohdN/..//.///////////////////
/////////////////////////////odddddddddhhooo/oNo//...//hho/.////////////////////
///////////...../////////////ohoooooohhhoooohhNdNhhhho/.oNdh/////////....///////
//////////////////////////////o/............../hh//oNddNh/////////...../////////
//////////////////////////////Nh////////........//.../ohNdo/////////////////////
/////////ooohhhNNNNdddddddddddddNNhhhhhhhhhhhhho/.//oooooho/..ohhhoooo//////////
NNdddssssdddNNhhhhoooooo//////Nso///////...//////////////..//ohhhNNNNddddddddNNN
hhooo///////////////////////oohsh///////////////////.////////////////////////ooo
////////ooohhhNNNdddssss------s--ssssssssddNNNNNNNNhhhNNNdddNNNhhhhoooo/////////
hNNddss------sssssssssssddsssss-ssssssssdddddddddddddddddddddddssssssssssssdddNN
----ssssdddddddddsss----      --           -sssssdds--sssssdddddddsdddddddddsss-
`, `////////////////////////////hN//////////////////////////////////////////////////
////////////////////////////hdho////////////////////////////////////////////////
oooooooo////////////////////hdsNhhhoo///////////////////////////////////oooooooo
ooooooooooooooooooooooooooooNNddoohhhNNhoooooooo/oo/oooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdNddNhooohhhhNNN/hhoooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohdhNNNN/hoo/hhNohhhhhNNhhooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohsoNNhddNohohoooohhN/..//ooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohshhhoNNNohhh/ohho/hhhho/..../oooooooooooooooooooooo
oooooooooooooooooooooooooooohsh/.........////////ooohhhoo/./hhhooooooooooooooooo
oooooooooooooooooooooooooooohshhhhooooo///.............//oooo/hNNhoooooooooooooo
oooooooooooooooooooooooooooohdNNdddddddddNNhhhhhhooooooo//.../..oNNhoooooooooooo
ooooooooooooooooooooo///////odh.////////ooo/////oooooooohNNho/...///////////////
/////////////////////////////Nh///////....................//ohNh/o//////////////
/////////////////////////////NNdddddddddddddNNNNNhoooo/////.../oNh//////////////
/////////./....//////////////hoooooooooohhhhhhhhhhNhooooooooho/..///////./...///
/////////////////////////////o//............................./hho../////////..//
/////////////////////////////oNo////////////////.............../h//////...//....
//////////oohhhNNNNdddddddddddddNNNNNNNNNNNNNNNNNNNNhhhhhhhhho/hNNNhhhhhooo////.
hNNdddssssddNNNhhhoooo////////dd///////.............../////////ooooohhhhNNNddddN
Nhhooo/////////////////////oooNsoooo//////////////////////////////////.....././/
/////////ooohhhNNdddssss-----ss----------s------sssdNNNNNNNddddNNNNNhhhoooo////.
ohNNddss-----ssssssssssdddsssss-ssssssssssssssddddddddddddddddddddsssssssssssssN
-----ssssddddddddsss----      -                   -dddds-sssssddddsddddddddddddd
`, `////////////////////////////dh//////////////////////////////////////////////////
////////////////////////////NNo/////////////////////////////////////////////////
ooooo//////////////////////oNdNNho///////////////////////////////////////////ooo
oooooooooooooooooooooooooooodNdhNdhooo//////////////////////////oooooooooooooooo
oooooooooooooooooooooooooooodNdNNdhdNooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooodNdNhNhNddhhoooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooodNNNoNddhNNddNhooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooddhhohhhhhNhdddh/ooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdh/......//hNsdo/./oooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdhhhhoooooohhNN//..../ohooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNshNNNNNNNNdddNNdNo/..../NNooooooooooooooooooooooooo
ooooooooooooooooooo/////////hd/.......////oooNdsNo....oNN///////////////////////
////////////////////////////odo////////........ohNNoo/.///No////////////////////
////////////////////////////oNNNNNNNdddddNNNNNo.../////ohNdNN/././..////////////
/////////////////////////////h//////oooohhhhNNNhooo//.........////////////./.../
/////////////////////////////o/................../oNddNdNNhhN//../....///.......
/////////////////////////////Nh///////////////......./ooooo//.////////////////..
////////ooohhhNNNNddddddddddddsNNNhhhhhhhhhhhhNNdddddddddNNNNNNNNNhhhhoooo/////.
NNdddsssdddNNNhhooooo////////hso/////////.............////////ooooohhhhNNNddddd/
hhoo/////////////////////oooohsNooo//////////////////////..///////////..////////
/////////oohhNNNdddsss------ss--ssssssssssssss-ssssssssssssddddNNNNhhhooooo/////
hhNddss-----ssssssssssddddssssssssssssssssssdddddddddddddddddddddsssssssssssssdo
----sssdddddddddsss----       -                  -------ssssdddddsdddddddNdddddo
`, `////////////////////////////ho//////////////////////////////////////////////////
///////////////////////////oNNo///////////////////////////////////////////////o/
oooooo/////////////////////oNdhho////////////////////////////////////////ooooooo
ooooooooooooooooooooooooooooddNohNoooo/////////////////////////ooooooooooooooooo
oooooooooooooooooooooooooooodNNhhohNNooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooodNdhhh/hNNhhoooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdNdNoNdooohNdhoooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdNNhoNNNohhooNhNhooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdNN....//////hNNNhoooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooddhooo/////.......//oooooooooooooooooooooooooooooooh
ooooooooooooooooooooooooooooddNdddNNNNNdNoo//....///oooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNd///////oooohoooohhoohhooo/////////////////////////
////////////////////////////hd/................//ohNdNddNNh/////////////////////
////////////////////////////hdNNdddNNNNhhhhoo/////../o/ohNddN///////////////////
////////////////////////////ohoohhhhhhhhhNNNNhhhhhhoo/......////////////////////
////////////////////////////o/....................//ohhoohhhhoo//////.//..../...
/////////////////////////////No///////................/ohNdNNNdh///////..///////
//////////ooohhhNNNNNdddddddddNNNhhhhhhhhhhhhhhhhhhho/../oooooohhoooo///////////
hNNdddssssddNNNhhhhoooooo////Nd///////........////////..../ooohhhNNNNdddddddNNNo
Nhhooo///////////////////////hso///////////////..................////....////oo/
/////////ooohhhNNNdddsssssssss-ssssssssssssssssdddNNNhhhhhhNNhhhhoooooo/////////
hhNNddss------ssssssssssddddsdssssssddddddddddddddddddddddddddssssssssssssdddNNo
-----sssdddddddddssss-----   --         ----------ssssssdddddddddsdddddddddsssso
`, `////////////////////////////oh//////////////////////////////////////////////oooo
////////////////////////////hdo///////////////////////////////////////////oooooo
oooooooooooo//////////////oohdNhohoo///////////////////////////ooooooooooooooooo
ooooooooooooooooooooooooooooNdNhhhNhhhoooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdNhhNNo/hNhohhooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdNNhhdNhooo/hhNohhooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNdNhhohNd/ohhhohohNNNNhooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooNsNNhhhoddNooo/oohh//oNNNhoooooooooooooooooooooooooo
ooooooooooooooooooooooooooohNsN/.oo/hNdoNNhooho......ooooooooooooooooooohhhhhhhh
hhhhhhhhhooooooooooooooooohhNsNo///.../ohhh/ohhhhoo//...//ooooooooooooohhhhhhhhh
ooooooooooooooooooooooooooooNsNdNNNNNo/////...//oohhhhhooooooooooooooooooooooooo
oooooooooooooooooooooooooooohdo/o/hhhNNNhoohoo/......//oohhNdNNh////////////////
////////////////////////////od/......../oooohddNhoo//....../oohdNo//////////////
////////////////////////////oNddNNdhhhhooooo//oooooohhhooo//.....///////////////
/////////////////////////////hhhhohhooooohNdsdo.......//oohhhhoo/.//////////////
/////////////////////////////o/............/ohNNhooo//......///oo///////........
/////////////////////////////Nh/////////........oohNhhhhooo//....///////////////
/////////ooohhhNNNNNdddddddddddNNNNNNNNNNNhhhhooo///hNNNNNNNNNNo////////../.....
NddddssssdddNNNhhhhooooooooooNso////////////////oooooohhhhhNNNNdddddddddNNNNhhoo
hhooo////////////////////////hsh///////////......////.............//////oooohhho
////////ooohhhNNNddddsssssssss--ssssssssddddNNdddddddNNNNhhhhooooo//////////////
hNdddss-------ssssssssssssddddsssssdddddddddddddddddddddssssssssssssssdddNNhhhho
----sssddddddddddssss-----   --      ---------ssssssdddddddddddddsdddddsss---ssh
`, `ooooo//oo///////////////////////////////////////////////////////oo/ooooooooooooo
oooooooooooooooooo/////o/o/ooNho//////////////////////oooooooooooooooooooooooooo
oooooooooooooooooooooooooooooddhoooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohdsdhNhhoooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohdddhhdNNNhooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohdNdNdNhdddNhNhhoooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohshdNhNhdNdhddNhhhhooooooooooooooooooooooooooooooooo
hhhhhhhhhhhhhhhoooooooohhhhhhshNhodddhdssddNhNhoooooooooooooooooooooohhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhohhhhoNNdNNssNhhoohNNhoo/oohhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNo/////.//////ohhhho/.//hNNho///ohhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhshNNNhhhhhoooooo//////ooo/..ohNho./hhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhNNdddddddddddsssddNh//ohhho/.oNho/ooooooooooooooo
/////////////////////////////do...../////oooohhNNddsh/../oNh..oh////////////////
/////////////////////////////dhoo//////............/oho/...oNh//////////////////
/////////////////////////////NNNNNNNNNNNNNNNNhhhhhoo../oho/..///////////////////
/////////////////////////////h///////oohhhNNNNNdddssd.../oo/////////////////////
/////////////////////////////ho//...............////ooo/...////.///////...//////
//////////////////oooooohhhhhNNoooooo////////////..../ooo///////////////////////
oohhNNNddddssssssssdddddddNNNdsNhhhhhhhhhhhhhhhhhhNhNdddddddddNNNNhhhhoo////////
dddNNhhhhoooo////////////////osN///////////////////////////ooooohhhhNNNdddddddN.
///////////////ooohhhhhNNNNNNN-dhhhooooooooooooooooo///////////////////////////.
oohhNNNddsss--------------ssss-sssssssssssssssssss---ssssssssdddNNNhhhooooo/////
-----------sssssdddddsssssssss--sssssssssddddddddddddddddddddssss------ssddddNN/
`, `ooooooooooooo//////////////////////////////////////////////ooooooooooooooooooooo
oooooooooooooooooooooooooooooNNoooooo///////oooo/ooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooNdNhooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooddNhhNhoooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooodNdhoNhhhNNhooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooosddNhNhhhhhhhNhhooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooohsddNhhoNNh/ohhhoNNNhooooooooooooooooooooooooooooohh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsdsNodNNoddNhohhNhNh/ooooooooooohhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhsddhohhhohNdhohhh/hNhhhNhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhddh/./......////////ooohdNhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddNNhNhhoooo//o/......./ooooohhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhooooooooooooooohddNNNNNddNNNNNNNddNhhhoooo//..//ooooooooooooooooooo
/////////////////////////////NN...........////ohooooohhhhhhooohhhh//////////////
/////////////////////////////NNhhhhooooo///..............//oohhhhNdh////////////
/////////////////////////////hNdddddddddddNNNhhhooo////.........../o////////////
/////////////////////////////h/..////////ooooohhhhhhhhhhhhhhoooo//...///////////
/////////////////////////////oo/////////............/////ooohhhhhhhhoh//////////
////////////////oooohhhhhhhhhhdhoooooooooooo//////////..........//oohh//////////
ohhNNddddssssssssdddddNNNNNNNNsdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhooo////ohhhooo/////
ddNNNhhooooo//////////////////sd///////////////////////////////oo///hhNNNddddddN
/////////////ooohhhhNNNNNNNdNNs-dNNNNhhhhhhoooooooooooo/////////////////////////
oohNNNddsss--------------sssss-ssssssssssssssssddddddddddddssssddddNNhhhhoooo/..
----------sssssddsssssssssss-------ssssssssssdddddddddddddddddddsss-----sssddh..
`, `ooooooooooo////////////////////////////////////////////////ooooooooooooooooooooo
oooooooooooooooooooooooooooodhooooooo///oo/ooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooddNhoooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdddhNNhohooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdNdhhNhohNNhhooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohshdNNNhddhhooNNNhhoooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohshNdhNhNhdNNhohhoNhoooooooooooooooooooooooooooooohhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhshNNoNdN/dssNoohhNoooo//oooooooooohhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhsNooooooohhhhhNNoh//.....//ohhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhsNo///../..../////ohhhhoo//./ohNhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhsNNddNhhhhhhhoohoo..///ohNNNh/../hhhhhhhhhhhhhhhhhhh
hhhhhhhhhhooooooooooooooooohdhhhNNNNNNNNNdddssdNho/..../ohho../Nhooooooooooooooo
////////////////////////////do............///ohhohhhoo//.../ooooh///////////////
////////////////////////////dhhhhoooooo///..........///ohoo/.../o///////////////
////////////////////////////NNNNNddddddddddddNNNNho/...../oooo//////////////////
////////////////////////////o/.....////ooohhhNNNddsNho//..../o//////////////////
////////////////////////////hh//////..............////ooho/..///////////////////
////////////oooohhhhhhNNNNNNNdhhooooooooooooooo///////...oho////////////////////
hNNdddsssssssddddNNNNNNhhhhhNsNoooooooooooooohhhhhNNNNNhoNddsdddddNNNNNhhooo////
NNhhoooo////////////////////osN/////////////////////////////////oooohhhNNNdddddd
//////////ooohhhhNNNNdddddddd-sdNNNhhhhhhhhhhhhhhhhooooooooo////////////////////
hNNdddss-------------ssssssss-ssssssssssssssssssssssddsssssssssssdddNNhhhoooo///
-------sssssdddssssssssss------------ssssssssdddddddddddddddddddssss-----ssddddh
`, `oooooooooo////////////////////////////////////////////////oooooooooooooooooooooo
ooooooooooooooo/oo//ooooooohNooo/o/////////////ooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdhoooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooNsdNNhooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooodNsN/Ndhooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooodNNdNhooNhhoooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooodNNdNh/hhhddhoooooooooooooooooooooooooooooooooooohhhh
hhhhhhhhoooooooooooooooohhhddhdoNNhohNhdhNhoooooooooooooooohhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhddhhoNNh/oNoNNddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhddo////...//hNNossNhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhNdhhhhhoo//../ooNsssNhooohhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhNdNddddddhhhhho/./ohNdssNh//ooooooooooooooooooooooooo
ooooooooooooooooooo//////ooNN////////////oho/.////ohdsdho///////////////////////
///////////////////////////hN//////......../ohhho/////ohddo/////////////////////
///////////////////////////oNddddddddNhooooo//NddddNho/../h/////////////////////
///////////////////////////ooooooooohhoooooohh/ohNNdddddNo./////////////////////
////////////////////////////o//............../h/..../ohhNNo/////////////////////
//////////////////////////ooNh/////////////....hho//..../o//////////////////////
///oohhhNNNdddddsssssssssssdddNNNNNNNNNNNNhhhhoodddddNNNddddNNNNNNhhhooo//////..
ssssdddNNNhhhooooooo//o/////Ns///////////./////.///oohho//oooohhhhNNNNNdddddd...
////////////////////oooohhhhN-Nooooooo////////////////////////////////////////..
///oohhhNNdddsss------------s---------ssddNNNNNNNNNNNNdssssddddNNNhhhhooooo/////
dss-------------ssssssdddssss-sssssssddddddddddddddddddddddsssss------sssdddddoo
`, `ooooooooooooooooooo////ooooooooo////////////oooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooohdoooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooohsdhoooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooNdshhNNhhooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooNNdd/hhhhdNhoooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooNNNddhohhhhhhNhhooooooooooooooooooooooooooooooooooohhh
ooooooooooooooooooooooooohNdNdhNohoh/hhNoNdNhooooooooooooooooooohhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhNdhNoddhoNhhohhhhhdooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhNdhoooNhohhh/hhNh/Nhohhoohhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhNdh//.///...////ooohNNdsdNhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhNdhdNNhhhoo//......../oohdssNhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhNNhNNdddsssdNhhhhoooo//..../hNNooooooooooooooo///ooooo
oooo//////////////////////hN/...///ooohhooohhhhNNhho/.///oo/////////////////////
//////////////////////////oNhooo///............//ohNNNhhhho/////////////////////
//////////////////////////oNNhNdNdsdNNNNhho///....../ohNNdssNho/////////////////
///////////////////////////o/..//ohhhNNddddNhhhhhho//.../ohNdssdo///////////////
///////////////////////////ho////........./////ooohNNhho...../ohNh//////////////
//////////////oooohhhhhhhNhNNhooooooooo/////......../ohNNho/.....///////////////
hhNNddddssssssssdddddNNNNNNdshhhhhhoooooooohhooooo//.../ohNddNhhoNNNNNhhhooo////
dNNhhhhooo/////////////////hsh///////////////////////...../hNNNNooohhhhNNNddddd.
////////////oooohhhhNNNNNNNN-dNhhhhoohoooooooooooooooo///...///////////////////.
ohhNNddsss--------------ssss-ssssssssssssdddddddddddddNdssddssssdddNNhhhhoooo///
----------sssssddsssssssssss----ssssssssssdddddddddddddddddddddssss-----sssddsN/
`, `oooooooooooooooooooooooooooooooo/////////ooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooodNooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooddNoooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooNshdNhooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooohNdNNdhhhooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooohNNdhhohNNhooooooooooooooooooooooooooooooooooooooohhhh
ooooooooooooooooooooooooohhNNdhoNNhohhhhoooooooooooooooooooooohhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhdhhdNoodhohNhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhdhooh/hhNhohooh//ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhNho////oNNhohhohhooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhNhNddNNohNhohh.../ohhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhoooooooooooooNhohNddN./ohNNho//../hNo/oooooooooooooooooooo/ooooooo
///////////////////////////No.....//..../oohhhoo/.oo////////////////////////////
///////////////////////////hhhooo/../o/.....//ohNNo/oo//////////////////////////
///////////////////////////hhhNddNNNNohhho/......ohdhhh/////////////////////////
///////////////////////////o/.//ooohdh./hNNhho/.....oNNN////////////////////////
///////////////////////////oh///...../...//ohhhhho//..odd///////////////////////
///////////oooohhhhNNNNNNNNNdhhooooo/.oho/....//ohhhNhoNNhoo////////////////////
NNNdddsssssssdddNNNNNhhhhhhhdNooooooo/.hhNNho/...../ohNhhddddssdddddddNNNNhhhoo/
NNhhhooo//////////////////ooNN//////////.//ohNhho//....o///////////ooooohhhNNNN.
///////////ooohhhNNNddddddddddNdNNNNNNNho/.../oohNhhhooohoooooo////////////////.
hhNNddss-------------ssssssssssssssssssssdNho/////ooNdssssssssssssssddNNNhhhhho/
-------ssssssddsssssssss----s -------sssssdddNhoooohNNddddddddddsddsss-----ssdh/
`, `ooooooooooooooooooooooooooooNooooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdhoooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdNoooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohsNhooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohdsdooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooohNddNooooooooooooooooooooooooooooooooooooohhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhNNshhhhhhhooooooohohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsNhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhh//sshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhoodNNhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhNshNdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
ooooooooooooooooooooooooooooh/o//hhoooooooooooooo////oo//oo/ooo/o////////ooooooo
////////////////////////////h....od/////////////////////////////////////////////
////////////////////////////Nhhh.hs/////////////////////////////////////////////
////////////////////////////hohd/Nso////////////////////////////////////////////
////////////////////////////o..//dso////////////////////////////////////////////
////////////////////////////oo/.oddo////////////////////////////////////////////
/////////oohhhhNNNdddddddddNho/.odd//sddddddddddddddddNNNNNNNhhhhoooo///////////
NdddssssssddNNNhhhhoooooooo/o/..hdd..N////////////oooooooohhhhhNNNNdddsddddddNN.
Nhhooo//////////////////////////hNh//do///////////////////////////////////ooooo.
////////oohhhNNddddssss---sdNho/NN///ss--------ssssssssddddNNNNhhhhhooo/////////
hNddss----------ssssssssssssddNoNo//hdNNdddddddddddddddddddsssss-ssssssssssddNNh
------ssssdssssssss------   ssdhh///NdhN----------sssssdddddddddsddddddddssss--s
`,
}
