package frames

// This is the value stored in the FrameMap
var NO = DefaultFrameType(NOFrames)

var myAnimationFrames = []string{
  `NNNNNNNN        NNNNNNNN        OOOOOOOOOOOOOOO
NNNNNNNNN       NNNNNNNN     OOOOOOOOOOOOOOOOOOO
NNNNNNNNNN      NNNNNNNN   OOOOOOOOOOOOOOOOOOOOO
NNNNNNNNNNN     NNNNNNNN  OOOOOOOOO       OOOOOOOOO
NNNNNNN NNNN    NNNNNNNN  OOOOOOOO           OOOOOOOO
NNNNNNN  NNNN   NNNNNNNN OOOOOOOO             OOOOOOOO
NNNNNNN   NNNN  NNNNNNNN OOOOOOOO             OOOOOOOO
NNNNNNN    NNNN NNNNNNNN OOOOOOOO             OOOOOOOO
NNNNNNN     NNNNNNNNNNNN  OOOOOOOO           OOOOOOOO
NNNNNNN      NNNNNNNNNNNN  OOOOOOOOO       OOOOOOOOO
NNNNNNN       NNNNNNNNNNNN   OOOOOOOOOOOOOOOOOOOOO
NNNNNNN        NNNNNNNNNNNN     OOOOOOOOOOOOOOOOO
NNNNNNN         NNNNNNNNNNNN        OOOOOOOOOOO
`
}
